//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestStatii {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestStatii() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XF.Common.RequestStatii", typeof(RequestStatii).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Http200 {
            get {
                return ResourceManager.GetString("Http200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Http201 {
            get {
                return ResourceManager.GetString("Http201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Http202 {
            get {
                return ResourceManager.GetString("Http202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Authoritative Information.
        /// </summary>
        public static string Http203 {
            get {
                return ResourceManager.GetString("Http203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Content.
        /// </summary>
        public static string Http204 {
            get {
                return ResourceManager.GetString("Http204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Content.
        /// </summary>
        public static string Http205 {
            get {
                return ResourceManager.GetString("Http205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Content.
        /// </summary>
        public static string Http206 {
            get {
                return ResourceManager.GetString("Http206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved Permanently.
        /// </summary>
        public static string Http301 {
            get {
                return ResourceManager.GetString("Http301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string Http302 {
            get {
                return ResourceManager.GetString("Http302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Other.
        /// </summary>
        public static string Http303 {
            get {
                return ResourceManager.GetString("Http303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Modified.
        /// </summary>
        public static string Http304 {
            get {
                return ResourceManager.GetString("Http304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Proxy.
        /// </summary>
        public static string Http305 {
            get {
                return ResourceManager.GetString("Http305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        public static string Http306 {
            get {
                return ResourceManager.GetString("Http306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Redirect.
        /// </summary>
        public static string Http307 {
            get {
                return ResourceManager.GetString("Http307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string Http400 {
            get {
                return ResourceManager.GetString("Http400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Http401 {
            get {
                return ResourceManager.GetString("Http401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Required.
        /// </summary>
        public static string Http402 {
            get {
                return ResourceManager.GetString("Http402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string Http403 {
            get {
                return ResourceManager.GetString("Http403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string Http404 {
            get {
                return ResourceManager.GetString("Http404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Not Allowed.
        /// </summary>
        public static string Http405 {
            get {
                return ResourceManager.GetString("Http405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Acceptable.
        /// </summary>
        public static string Http406 {
            get {
                return ResourceManager.GetString("Http406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Authentication Required.
        /// </summary>
        public static string Http407 {
            get {
                return ResourceManager.GetString("Http407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Timeout.
        /// </summary>
        public static string Http408 {
            get {
                return ResourceManager.GetString("Http408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        public static string Http409 {
            get {
                return ResourceManager.GetString("Http409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gone.
        /// </summary>
        public static string Http410 {
            get {
                return ResourceManager.GetString("Http410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length required.
        /// </summary>
        public static string Http411 {
            get {
                return ResourceManager.GetString("Http411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition failed.
        /// </summary>
        public static string Http412 {
            get {
                return ResourceManager.GetString("Http412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Entity too large.
        /// </summary>
        public static string Http413 {
            get {
                return ResourceManager.GetString("Http413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URI too long.
        /// </summary>
        public static string Http414 {
            get {
                return ResourceManager.GetString("Http414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Mediatype.
        /// </summary>
        public static string Http415 {
            get {
                return ResourceManager.GetString("Http415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested range not satisfieable.
        /// </summary>
        public static string Http416 {
            get {
                return ResourceManager.GetString("Http416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expectation failed.
        /// </summary>
        public static string Http417 {
            get {
                return ResourceManager.GetString("Http417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string Http500 {
            get {
                return ResourceManager.GetString("Http500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented.
        /// </summary>
        public static string Http501 {
            get {
                return ResourceManager.GetString("Http501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad gateway.
        /// </summary>
        public static string Http502 {
            get {
                return ResourceManager.GetString("Http502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service unavailable.
        /// </summary>
        public static string Http503 {
            get {
                return ResourceManager.GetString("Http503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway timeout.
        /// </summary>
        public static string Http504 {
            get {
                return ResourceManager.GetString("Http504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP version not supported.
        /// </summary>
        public static string Http505 {
            get {
                return ResourceManager.GetString("Http505", resourceCulture);
            }
        }
    }
}
